### ISSUE TITLE
Use requestAnimationFrame rather than setTimeout

### ISSUE THREAD

**Issue by Pomax** [s-macke/VoxelSpace#15]
Since your repo got on the hackernews front page: your [draw loop](https://github.com/s-macke/VoxelSpace/blob/gh-pages/VoxelSpace.html#L422-L438) uses `window.setTimeout(..., 0)`, but this leads to rather jarring stutter. Replacing `window.setTimeout(...)` with `window.requestAnimationFrame(Draw)` lets the code run much smoother.

On a secondary note, a setTimeout with `0` as argument doesn't actually run "immediately"; it has 20 years of legacy baggage and depending on the browser you're basically guaranteed a minimum interval of 3 to 5 milliseconds instead (because in the 90s, not every browser could _do_ immediate timeouts, and so the lower bound was capped. Then the spec folks went "we should formalize that behaviour" rather than not doing that...)

**Comment by s-macke** [comment]
Thanks for the information. I switched to requestAnimationFrame.
