### ISSUE TITLE
Any plans to port Delta Force to it ?

### ISSUE THREAD

**Issue by pratikone** [s-macke/VoxelSpace#16]
Delta Force games will benefit greatly from running on a modern voxel engine in terms of  higher resolution, widescreen, multi platform incl web,  game controller support and even modding. Any plans in that direction?

**Comment by Not-Nik** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/Delta_Force_(video_game)): `Delta Force uses NovaLogic's own proprietary Voxel Space engine [...]`. Same goes for its [second installation](https://en.wikipedia.org/wiki/Delta_Force_2): `The game continues to use NovaLogic's proprietary Voxel Space engine from its earlier games`. Also, this repository is just here to showcase the technology and is not affiliated with NovaLogic as far as I'm concerned.

**Comment by pratikone** [comment]
thanks. I realized that too later
