### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by IBPX** [s-macke/VoxelSpace#2]
Hi! There doesn't seem to be a license for this project. [choosealicense.com](https://choosealicense.com) explains some of your choices.

[MIT](https://choosealicense.com/licenses/mit/) is a very simple, do-whatever-you-want-but-give-credit license. The [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) ensures that you get back modifications. If you chose the GPL, you might license the maps as [CC BY](https://creativecommons.org/licenses/by/4.0/) or [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) 4.0, which are one-way compatible with the GPL (CC --> GPL).

**Comment by DmitryOlkhovoi** [comment]
License patrol lol

**Comment by theronic** [comment]
Would also like to know :) I would love to use this for an art + code project

**Comment by s-macke** [comment]
I would really like to put this project under a permissive license. However there are two problems.
1. The color and height maps are reverse engineered from the game Comanche. So putting them under a license is simply not possible.
2. The algorithm might be still patented in some countries by Novalogic. So the license must not violate a potential patent. Be aware if you want to use it commercially.

So the license text must at least warn about these issues.

**Comment by s-macke** [comment]
I added the MIT license and wrote 3 sentences in the README. I hope this is enough.
