### ISSUE TITLE
View broken on mobile phones

### ISSUE THREAD

**Issue by KidLinus** [s-macke/VoxelSpace#6]
Application loads the initial terrain fine but the second you click anywhere the camera flies into the ground and you can't do anything else.

**Comment by Snabel** [comment]
In case that this is only me, I'm using Android 7.0, Chrome 62.0.3202 and I'm loading the demo

**Comment by hex007** [comment]
Can you try again it on Firefox?

**Comment by Snabel** [comment]
On Firefox I can go straight forward whilst holding down my finger at any point in the view. Solid 18 fps unlike the 3fps chrome had. No way of looking around.

**Comment by s-macke** [comment]
Problem might be, that the mouse movement does not take into account different screen resolutions. I have changed this part. Can you try it again?

**Comment by Snabel** [comment]
No, still not working in chrome. I think you need to take the ontouch events into account for these devices. The phone tries to scroll, zoom and do other gestures since it does not recognize the fact that the view can be interacted with.

**Comment by s-macke** [comment]
I fixed at least one problem with the touch screen event. On my IPad with Safari it works without any problem. 
However, Chrome on my mobile is strange. It shows the terrain upside down with an older version on Chrome and with a new version of Chrome it just shows a yellow screen.

**Comment by klokkenman1** [comment]
I found that if you add the pointer events the demo works on chrome desktop in mobile debugging
